// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB-4I6niL5hzaxDsWW8KQ7ryGIlGqxqeI',
    appId: '1:1016372339085:web:9a02eabc859cc7c286ddc4',
    messagingSenderId: '1016372339085',
    projectId: 'koliagonotification',
    authDomain: 'koliagonotification.firebaseapp.com',
    storageBucket: 'koliagonotification.firebasestorage.app',
    measurementId: 'G-416VY95GHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiXiDfXqyKaKLc98E_Ndc__whvoY7BeRU',
    appId: '1:1016372339085:android:df71b1a81955f24486ddc4',
    messagingSenderId: '1016372339085',
    projectId: 'koliagonotification',
    storageBucket: 'koliagonotification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtPxexub-N3_hyjhkx4b-jA4PJ8AEWZBY',
    appId: '1:1016372339085:ios:07802aef1cc3c4e186ddc4',
    messagingSenderId: '1016372339085',
    projectId: 'koliagonotification',
    storageBucket: 'koliagonotification.firebasestorage.app',
    iosBundleId: 'com.example.vlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtPxexub-N3_hyjhkx4b-jA4PJ8AEWZBY',
    appId: '1:1016372339085:ios:07802aef1cc3c4e186ddc4',
    messagingSenderId: '1016372339085',
    projectId: 'koliagonotification',
    storageBucket: 'koliagonotification.firebasestorage.app',
    iosBundleId: 'com.example.vlog',
  );
}
